--- #YAML:1.0
name:               VendorAPI-2Checkout-Client
version:            0.05
abstract:           an OO interface to the 2Checkout.com Vendor API
author:
    - Len Jaffe <lenjaffe@jaffesystems.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:   0.87
    XML::Simple:  0
requires:
    LWP:               0
    Params::Validate:  0
    URI:               0
    URI::QueryParam:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
